version: "3"

services:
  anime-site-front:
    container_name: anime-site-front
    build:
      context: .
      dockerfile: ./apps/anime-site-front/Dockerfile
    restart: always
    ports:
      - 5173:5173
    networks:
      - app_network
  anime-site-backend:
    container_name: anime-site-backend
    build:
      context: .
      dockerfile: ./apps/anime-site-backend/Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
